import * as Lucide from "lucide-react";
import * as Simple from "@icons-pack/react-simple-icons";

export const Icons = {
  "pdf": <Lucide.FileText />,
  "txt": <Lucide.FileText />,
  "html": <Simple.SiHtml5 style={{ color: Simple.SiHtml5Hex }} />,
  "db": <Lucide.Database />,
  "png": <Lucide.FileImage />,
  "jpg": <Lucide.FileImage />,
  "jpeg": <Lucide.FileImage />,
  "gif": <Lucide.FileImage />,
  "mp4": <Lucide.FileVideo />,
  "mov": <Lucide.FileVideo />,
  "avi": <Lucide.FileVideo />,
  "mp3": <Lucide.FileMusic />,
  "wav": <Lucide.FileMusic />,
  "flac": <Lucide.FileMusic />,
  "ogg": <Lucide.FileMusic />,
  "zip": <Lucide.FileArchive />,
  "rar": <Lucide.FileArchive />,
  "7z": <Lucide.FileArchive />,
  "tar": <Lucide.FileArchive />,
  "gz": <Lucide.FileArchive />,
  "bz2": <Lucide.FileArchive />,
  "xz": <Lucide.FileArchive />,
  "exe": <Lucide.FileTerminal />,
  "dll": <Lucide.FileTerminal />,
  "so": <Lucide.FileTerminal />,
  "bin": <Lucide.FileTerminal />,
  ".gitignore": <Simple.SiGit style={{ color: Simple.SiGitHex }} />,
  ".gitkeep": <Simple.SiGit style={{ color: Simple.SiGitHex }} />,
  ".npmrc": <Simple.SiNpm style={{ color: Simple.SiNpmHex }} />,
  ".npmignore": <Simple.SiNpm style={{ color: Simple.SiNpmHex }} />,
  "package.json": <Simple.SiNodedotjs style={{ color: Simple.SiNodedotjsHex }} />,
}